const $=selector=>document.querySelector(selector);
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={protection_observed:'Protection observed',potential_weakness:'Potential weakness',unable_to_assess:'Unable to assess',not_applicable:'Not applicable'};
let assessments=[],current,view='overview';
const badge=f=>`<span class="badge ${esc(f.status)}">${esc(labels[f.status]||f.status)}</span>`;
const evidence=e=>`<div><span class="badge">${esc(e.id)} · ${esc(e.type)}</span><small class="muted">${esc(e.collectedAt)}</small><pre>${esc(e.observedValue)}</pre><p>Source: ${esc(e.source)} · Sensitive fields omitted or redacted.</p></div>`;
function finding(f,report=false){return `<details ${report?'open':''}><summary><strong>${esc(f.title)}</strong>${badge(f)}<span class="badge">${esc(f.severity)}</span><span class="badge">${esc(f.confidence)} confidence</span></summary><p>${esc(f.checkId)} · ${esc(f.observation)}</p><h3>Why it matters & limitations</h3><p>${esc(f.impact)}</p><h3>Recommendation</h3><p>${esc(f.recommendation)}</p><h3>Why am I seeing this?</h3>${f.evidenceIds.map(id=>evidence(current.evidence.find(e=>e.id===id))).join('')}<h3>Validation</h3><p>${esc(f.validation)}</p>${report?'':`<button class="secondary" data-check="${esc(f.checkId)}">Verify fix</button> <select aria-label="Finding lifecycle" data-lifecycle="${esc(f.id)}">${['new','acknowledged','investigating','accepted risk','fixed','needs verification','verified','false positive'].map(s=>`<option ${f.lifecycle===s?'selected':''}>${s}</option>`).join('')}</select>`}</details>`;}
const table=(heads,rows)=>`<table><thead><tr>${heads.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(v=>`<td>${esc(v)}</td>`).join('')}</tr>`).join('')}</tbody></table>`;
function render(){
  document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));
  $('#heading').textContent=({overview:'Assessment overview',evidence:'Evidence explorer',coverage:'Assessment coverage',technology:'Technology profile',history:'Assessment history',methodology:'Methodology & privacy',findings:'Findings',resources:'Resource inspection'})[view];
  for(const id of ['verify','export','report','html'])$('#'+id).disabled=!current;
  $('#target').innerHTML=current?`<div class="target"><div><strong>${esc(current.url)}</strong><div class="muted">${esc(new Date(current.createdAt).toLocaleString())} · Passive inspection</div></div><div>${current.checksCompleted} / ${current.checksTotal} checks completed<br><small class="muted">${current.durationMs} ms · SiteLens ${esc(current.version)}</small></div></div>`:'';
  if(view==='methodology'){$('#content').innerHTML=`<div class="card"><h2>What SiteLens inspects</h2><p>SiteLens reads the selected document’s DOM and security-relevant response headers captured by the browser after site access is granted. It does not send test requests, submit forms or inject attack payloads. Reload a website after granting access to capture its document response.</p><h3>Scope and interpretation</h3><p>Header presence is a configuration observation. CSP policy quality, TLS configuration, authentication, authorization, backend frameworks, databases and business logic are not established by this assessment. DOM resources may differ from actual network requests. Technology indicators are heuristic and versions are unknown.</p><h3>Privacy</h3><p>Up to 50 assessments are stored locally. Cookie values, storage contents, form values and page text are not collected. URL credentials, fragments and query strings are omitted. Security header values may contain site configuration; review exports before sharing. Site permissions can be revoked through Chrome’s extension settings.</p><button id="delete" class="secondary">Delete all local assessments</button><h3>Check methodology</h3>${table(['Check','Method'],[['SL-TLS-001','Inspect document URL scheme'],['SL-CSP-001','Inspect response CSP and DOM CSP meta presence'],['SL-HEADER-001','Check HTTPS and positive HSTS max-age'],['SL-HEADER-002','Check exact nosniff header value'],['SL-HEADER-003','Observe Referrer-Policy presence; effectiveness not graded'],['SL-HEADER-004','Check DENY / SAMEORIGIN or CSP frame-ancestors presence'],['SL-RESOURCE-001','Find HTTP DOM references on HTTPS pages'],['SL-RESOURCE-002','Inspect third-party script / stylesheet integrity attributes'],['SL-FORM-001','Inspect declared password form action scheme'],['SL-COOKIE-001','Unavailable; attributes not collected']])}<p>References: <a href="https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers">MDN HTTP headers</a> · <a href="https://owasp.org/www-project-secure-headers/">OWASP Secure Headers Project</a></p></div>`;$('#delete').onclick=async()=>{await chrome.storage.local.remove('assessments');assessments=[];current=null;render();};return;}
  if(view==='history'){$('#content').innerHTML=`<div class="card"><h2>Saved assessments</h2>${assessments.map(a=>`<p><button class="secondary" data-assessment="${esc(a.id)}">${esc(new Date(a.createdAt).toLocaleString())} · ${esc(a.url)}</button></p>`).join('')||'<p>No assessments yet.</p>'}</div>`;return;}
  if(!current){$('#content').innerHTML='<div class="card empty"><h2>Your evidence workspace is ready</h2><p>Open a website, click the SiteLens extension, and choose Inspect current website.</p></div>';return;}
  if(view==='overview'){
    const counts=['protection_observed','potential_weakness','unable_to_assess','not_applicable'].map(status=>({status,count:current.findings.filter(f=>f.status===status).length}));
    const previous=assessments.find(a=>a.id!==current.id&&a.url===current.url&&a.createdAt<current.createdAt);
    const changes=previous?current.findings.filter(f=>previous.findings.find(p=>p.checkId===f.checkId)?.status!==f.status):[];
    $('#content').innerHTML=`<div class="stats">${counts.map(c=>`<div class="stat"><strong>${c.count}</strong><span>${labels[c.status]}</span></div>`).join('')}</div><div class="card"><h2>A browser-visible assessment, with boundaries</h2><p>This assessment records observed configuration and potential weaknesses. It does not certify that this website is secure. Expand each finding to inspect its evidence and limitations.</p></div><div class="two"><div class="card"><h2>Needs your attention</h2>${current.findings.filter(f=>f.status==='potential_weakness').map(f=>`<p>${badge(f)} ${esc(f.title)}</p>`).join('')||'<p>No potential weaknesses observed by these checks.</p>'}</div><div class="card"><h2>Changes since previous assessment</h2>${previous?changes.map(f=>`<p>${esc(f.title)} → ${esc(labels[f.status])}</p>`).join('')||'<p>No finding status changes observed. Consult raw evidence for policy changes.</p>':'<p>Inspect this URL again to compare observations.</p>'}</div></div>`;
  }else if(view==='findings')$('#content').innerHTML=current.findings.map(f=>finding(f)).join('');
  else if(view==='evidence')$('#content').innerHTML=current.evidence.map(e=>`<details><summary>${esc(e.id)} · ${esc(e.type)}</summary>${evidence(e)}<h3>Dependent findings</h3>${current.findings.filter(f=>f.evidenceIds.includes(e.id)).map(f=>`<p>${esc(f.checkId)} · ${esc(f.title)}</p>`).join('')}</details>`).join('');
  else if(view==='coverage')$('#content').innerHTML=`<div class="card"><h2>What was assessed</h2>${table(['Area','Coverage'],current.coverage.map(c=>[c.area,c.status]))}<p>Completed checks indicate available evidence, not whole-application test coverage.</p></div>`;
  else if(view==='technology')$('#content').innerHTML=`<div class="card"><h2>Observed technology indicators</h2>${table(['Technology','Confidence','Evidence','Version'],current.technologies.map(t=>[t.name,t.confidence,t.observation,'Unknown']))}<p>Backend frameworks and databases cannot be established from these indicators.</p></div>`;
  else if(view==='resources')$('#content').innerHTML=`<div class="card"><h2>Document resource references</h2>${table(['URL','Type','Origin','Integrity','Crossorigin'],current.resources.map(r=>[r.url,r.type,r.thirdParty?'Third party':'Same origin',r.integrity||'Not observed',r.crossorigin||'Not specified']))}</div>`;
}
async function verify(checkId){
  $('#notice').textContent='Inspecting the website again…';
  try{const previous=current;const response=await chrome.runtime.sendMessage({type:'inspect',tabId:current.tabId});if(response.error)throw new Error(response.error);await load(response.id);
    if(checkId){const before=previous.findings.find(f=>f.checkId===checkId),after=current.findings.find(f=>f.checkId===checkId);const improved=before.status==='potential_weakness'&&after.status==='protection_observed';$('#notice').textContent=`${after.title}: ${labels[before.status]} → ${labels[after.status]}. ${improved?'Improvement observed in this check.':'Review the new evidence; a fix has not been verified.'} The document must be reloaded to refresh header evidence.`;view='findings';render();}
    else $('#notice').textContent='New assessment saved. Reload the website before re-inspecting to refresh response headers.';
  }catch(e){$('#notice').textContent=e.message+' Open the target website and inspect it from the extension if its original tab is closed.';}
}
function download(name,type,body){const url=URL.createObjectURL(new Blob([body],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function report(){return `<h1>SiteLens · Website Security Assessment</h1><p>${esc(current.url)}<br>${esc(current.createdAt)} · Passive inspection · SiteLens ${esc(current.version)}</p><h2>Executive summary & scope</h2><p>${current.checksCompleted} / ${current.checksTotal} checks completed. This report documents browser-visible observations and does not certify application security. No active attacks were performed. Cookie attributes, authentication, authorization, databases, business logic and TLS protocol configuration were not assessed. Technology fingerprints are heuristic.</p><h2>Coverage & limitations</h2>${table(['Area','Coverage'],current.coverage.map(c=>[c.area,c.status]))}<h2>Findings, evidence & recommendations</h2>${current.findings.map(f=>finding(f,true)).join('')}<h2>Technology profile</h2>${table(['Name','Confidence','Indicator'],current.technologies.map(t=>[t.name,t.confidence,t.observation]))}<h2>Resource assessment</h2>${table(['URL','Type','Integrity'],current.resources.map(r=>[r.url,r.type,r.integrity||'Not observed']))}<h2>Methodology & references</h2><p>Inspect document URL, DOM resource and form attributes, technology markers and captured response security headers. Stable check IDs identify each method. Header presence does not prove policy effectiveness. Sensitive fields are omitted; URL query strings and credentials are redacted.</p><p>https://owasp.org/www-project-secure-headers/<br>https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers</p>`;}
$('#navigation').onclick=e=>{if(e.target.dataset.view){view=e.target.dataset.view;render();}};
$('#content').onclick=e=>{if(e.target.dataset.check)verify(e.target.dataset.check);if(e.target.dataset.assessment){current=assessments.find(a=>a.id===e.target.dataset.assessment);view='overview';render();}};
$('#content').onchange=async e=>{if(e.target.dataset.lifecycle){current.findings.find(f=>f.id===e.target.dataset.lifecycle).lifecycle=e.target.value;await chrome.storage.local.set({assessments});}};
$('#verify').onclick=()=>verify();
$('#export').onclick=()=>{const {tabId,...portable}=current;download('sitelens-assessment.json','application/json',JSON.stringify(portable,null,2));};
$('#html').onclick=()=>download('sitelens-report.html','text/html',`<!doctype html><html lang="en"><meta charset="utf-8"><title>SiteLens assessment</title><style>body{font:14px system-ui;max-width:1000px;margin:40px auto;padding:20px}table{width:100%;text-align:left}td,th{padding:10px;border-bottom:1px solid #ddd}pre{white-space:pre-wrap;overflow-wrap:anywhere}details{margin:20px 0}</style>${report()}</html>`);
$('#report').onclick=()=>{const saved=$('#content').innerHTML;$('#content').innerHTML=report();window.print();$('#content').innerHTML=saved;};
async function load(id){({assessments=[]}=await chrome.storage.local.get('assessments'));current=assessments.find(a=>a.id===id)||assessments[0];render();}
await load(new URLSearchParams(location.search).get('id'));
