// Generated by scripts/generate-technology-logos.mjs.
export const TECHNOLOGY_LOGOS: Record<string,{file:string}> = {
  "ASP.NET": {
    "file": "aspnet.svg"
  },
  "AWS CloudFront": {
    "file": "awscloudfront.svg"
  },
  "Adobe Fonts": {
    "file": "adobefonts.svg"
  },
  "Alpine.js": {
    "file": "alpinejs.svg"
  },
  "Amplitude": {
    "file": "amplitude.svg"
  },
  "Angular": {
    "file": "angular.svg"
  },
  "Apache": {
    "file": "apache.svg"
  },
  "Astro": {
    "file": "astro.svg"
  },
  "Axios": {
    "file": "axios.svg"
  },
  "Bootstrap": {
    "file": "bootstrap.svg"
  },
  "Chart.js": {
    "file": "chartjs.svg"
  },
  "Cloudflare": {
    "file": "cloudflare.svg"
  },
  "Cloudflare Browser Insights": {
    "file": "cloudflarebrowserinsights.svg"
  },
  "Cloudflare Turnstile": {
    "file": "cloudflareturnstile.svg"
  },
  "Crisp": {
    "file": "crisp.png"
  },
  "D3.js": {
    "file": "d3js.svg"
  },
  "Datadog": {
    "file": "datadog.svg"
  },
  "Django": {
    "file": "django.svg"
  },
  "Docusaurus": {
    "file": "docusaurus.svg"
  },
  "Drupal": {
    "file": "drupal.svg"
  },
  "Express": {
    "file": "express.svg"
  },
  "Fastly": {
    "file": "fastly.svg"
  },
  "Firebase": {
    "file": "firebase.svg"
  },
  "Framer Motion": {
    "file": "framermotion.svg"
  },
  "GSAP": {
    "file": "gsap.svg"
  },
  "Gatsby": {
    "file": "gatsby.svg"
  },
  "Ghost": {
    "file": "ghost.svg"
  },
  "Google Analytics": {
    "file": "googleanalytics.svg"
  },
  "Google Fonts": {
    "file": "googlefonts.svg"
  },
  "Google Tag Manager": {
    "file": "googletagmanager.svg"
  },
  "Google reCAPTCHA": {
    "file": "googlerecaptcha.svg"
  },
  "HTMX": {
    "file": "htmx.svg"
  },
  "Hotjar": {
    "file": "hotjar.svg"
  },
  "HubSpot": {
    "file": "hubspot.svg"
  },
  "Hugo": {
    "file": "hugo.svg"
  },
  "Intercom": {
    "file": "intercom.svg"
  },
  "Jekyll": {
    "file": "jekyll.svg"
  },
  "Joomla": {
    "file": "joomla.svg"
  },
  "Laravel": {
    "file": "laravel.svg"
  },
  "Lenis": {
    "file": "lenis.png"
  },
  "LiteSpeed": {
    "file": "litespeed.png"
  },
  "Lodash": {
    "file": "lodash.svg"
  },
  "Lucide": {
    "file": "lucide.svg"
  },
  "Magento": {
    "file": "magento.svg"
  },
  "Matomo": {
    "file": "matomo.svg"
  },
  "Microsoft Clarity": {
    "file": "microsoftclarity.svg"
  },
  "Microsoft IIS": {
    "file": "microsoftiis.svg"
  },
  "Mixpanel": {
    "file": "mixpanel.svg"
  },
  "Netlify": {
    "file": "netlify.svg"
  },
  "New Relic": {
    "file": "newrelic.svg"
  },
  "Next.js": {
    "file": "nextjs.svg"
  },
  "Nginx": {
    "file": "nginx.svg"
  },
  "Nuxt.js": {
    "file": "nuxtjs.svg"
  },
  "PHP": {
    "file": "php.svg"
  },
  "PayPal": {
    "file": "paypal.svg"
  },
  "Plausible": {
    "file": "plausible.svg"
  },
  "PostHog": {
    "file": "posthog.svg"
  },
  "React": {
    "file": "react.svg"
  },
  "React Router": {
    "file": "reactrouter.svg"
  },
  "React Three Drei": {
    "file": "reactthreedrei.svg"
  },
  "React Three Fiber": {
    "file": "reactthreefiber.svg"
  },
  "Segment": {
    "file": "segment.svg"
  },
  "Sentry": {
    "file": "sentry.svg"
  },
  "Shopify": {
    "file": "shopify.svg"
  },
  "Squarespace": {
    "file": "squarespace.svg"
  },
  "Stripe": {
    "file": "stripe.svg"
  },
  "Svelte": {
    "file": "svelte.svg"
  },
  "Tailwind CSS": {
    "file": "tailwindcss.svg"
  },
  "Tawk.to": {
    "file": "tawkto.png"
  },
  "Three.js": {
    "file": "threejs.svg"
  },
  "UNPKG": {
    "file": "unpkg.svg"
  },
  "Vercel": {
    "file": "vercel.svg"
  },
  "Vite": {
    "file": "vite.svg"
  },
  "Vue.js": {
    "file": "vuejs.svg"
  },
  "Webflow": {
    "file": "webflow.svg"
  },
  "Wix": {
    "file": "wix.svg"
  },
  "WooCommerce": {
    "file": "woocommerce.svg"
  },
  "WordPress": {
    "file": "wordpress.svg"
  },
  "Zendesk": {
    "file": "zendesk.svg"
  },
  "cdnjs": {
    "file": "cdnjs.svg"
  },
  "hCaptcha": {
    "file": "hcaptcha.svg"
  },
  "jQuery": {
    "file": "jquery.svg"
  },
  "jsDelivr": {
    "file": "jsdelivr.svg"
  }
};
